# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import room_pb2 as room__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='control.proto',
  package='control',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  serialized_pb=b'\n\rcontrol.proto\x12\x07\x63ontrol\x1a\x1bgoogle/protobuf/empty.proto\x1a\nroom.proto\"\x15\n\x05Hello\x12\x0c\n\x04text\x18\x01 \x01(\t25\n\x08Greeting\x12)\n\x05World\x12\x0e.control.Hello\x1a\x0e.control.Hello\"\x00\x42\x06Z\x04.;pbb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,room__pb2.DESCRIPTOR,])




_HELLO = _descriptor.Descriptor(
  name='Hello',
  full_name='control.Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='control.Hello.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Hello'] = _HELLO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hello = _reflection.GeneratedProtocolMessageType('Hello', (_message.Message,), {
  'DESCRIPTOR' : _HELLO,
  '__module__' : 'control_pb2'
  # @@protoc_insertion_point(class_scope:control.Hello)
  })
_sym_db.RegisterMessage(Hello)


DESCRIPTOR._options = None

_GREETING = _descriptor.ServiceDescriptor(
  name='Greeting',
  full_name='control.Greeting',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=90,
  serialized_end=143,
  methods=[
  _descriptor.MethodDescriptor(
    name='World',
    full_name='control.Greeting.World',
    index=0,
    containing_service=None,
    input_type=_HELLO,
    output_type=_HELLO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETING)

DESCRIPTOR.services_by_name['Greeting'] = _GREETING

# @@protoc_insertion_point(module_scope)
