# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurement.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

from . import room_pb2 as room__pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='measurement.proto',
  package='measurement',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  serialized_pb=b'\n\x11measurement.proto\x12\x0bmeasurement\x1a\x1bgoogle/protobuf/empty.proto\x1a\nroom.proto\"\x82\x01\n\x0bMeasurement\x12&\n\x0broom_number\x18\x01 \x01(\x0e\x32\x11.room.RoomNumbers\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x1c.measurement.MeasurementType\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x10\n\x08\x64\x61tetime\x18\x04 \x01(\x03\"@\n\x12MeasurementRequest\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.measurement.MeasurementType\"d\n\x13MeasurementResponse\x12-\n\x0bmeasurement\x18\x01 \x01(\x0b\x32\x18.measurement.Measurement\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\x08\"6\n\x0eInsertResponse\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\x08J\x04\x08\x01\x10\x02\"G\n\x0e\x41vailableTypes\x12\x35\n\x0f\x61vailable_types\x18\x01 \x03(\x0e\x32\x1c.measurement.MeasurementType*Y\n\x0fMeasurementType\x12\x0f\n\x0bTEMPERATURE\x10\x00\x12\x0c\n\x08HUMIDITY\x10\x01\x12\x10\n\x0c\x41IR_PRESSURE\x10\x02\x12\x15\n\x11\x43O2_CONCENTRATION\x10\x03\x32\xad\x01\n\x13MeasurementRecorder\x12J\n\x03Get\x12\x1f.measurement.MeasurementRequest\x1a .measurement.MeasurementResponse\"\x00\x12J\n\x11GetAvailableTypes\x12\x16.google.protobuf.Empty\x1a\x1b.measurement.AvailableTypes\"\x00\x32Y\n\x10MeasurementStore\x12\x45\n\nInsertData\x12\x18.measurement.Measurement\x1a\x1b.measurement.InsertResponse\"\x00\x42\x06Z\x04.;pbb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,room__pb2.DESCRIPTOR,])

_MEASUREMENTTYPE = _descriptor.EnumDescriptor(
  name='MeasurementType',
  full_name='measurement.MeasurementType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEMPERATURE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HUMIDITY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AIR_PRESSURE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CO2_CONCENTRATION', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=505,
  serialized_end=594,
)
_sym_db.RegisterEnumDescriptor(_MEASUREMENTTYPE)

MeasurementType = enum_type_wrapper.EnumTypeWrapper(_MEASUREMENTTYPE)
TEMPERATURE = 0
HUMIDITY = 1
AIR_PRESSURE = 2
CO2_CONCENTRATION = 3



_MEASUREMENT = _descriptor.Descriptor(
  name='Measurement',
  full_name='measurement.Measurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_number', full_name='measurement.Measurement.room_number', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='measurement.Measurement.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='measurement.Measurement.value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='measurement.Measurement.datetime', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=206,
)


_MEASUREMENTREQUEST = _descriptor.Descriptor(
  name='MeasurementRequest',
  full_name='measurement.MeasurementRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='measurement.MeasurementRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=272,
)


_MEASUREMENTRESPONSE = _descriptor.Descriptor(
  name='MeasurementResponse',
  full_name='measurement.MeasurementResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measurement', full_name='measurement.MeasurementResponse.measurement', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='measurement.MeasurementResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='measurement.MeasurementResponse.error', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=374,
)


_INSERTRESPONSE = _descriptor.Descriptor(
  name='InsertResponse',
  full_name='measurement.InsertResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='measurement.InsertResponse.message', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='measurement.InsertResponse.error', index=1,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=430,
)


_AVAILABLETYPES = _descriptor.Descriptor(
  name='AvailableTypes',
  full_name='measurement.AvailableTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='available_types', full_name='measurement.AvailableTypes.available_types', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=503,
)

_MEASUREMENT.fields_by_name['room_number'].enum_type = room__pb2._ROOMNUMBERS
_MEASUREMENT.fields_by_name['type'].enum_type = _MEASUREMENTTYPE
_MEASUREMENTREQUEST.fields_by_name['type'].enum_type = _MEASUREMENTTYPE
_MEASUREMENTRESPONSE.fields_by_name['measurement'].message_type = _MEASUREMENT
_AVAILABLETYPES.fields_by_name['available_types'].enum_type = _MEASUREMENTTYPE
DESCRIPTOR.message_types_by_name['Measurement'] = _MEASUREMENT
DESCRIPTOR.message_types_by_name['MeasurementRequest'] = _MEASUREMENTREQUEST
DESCRIPTOR.message_types_by_name['MeasurementResponse'] = _MEASUREMENTRESPONSE
DESCRIPTOR.message_types_by_name['InsertResponse'] = _INSERTRESPONSE
DESCRIPTOR.message_types_by_name['AvailableTypes'] = _AVAILABLETYPES
DESCRIPTOR.enum_types_by_name['MeasurementType'] = _MEASUREMENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Measurement = _reflection.GeneratedProtocolMessageType('Measurement', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENT,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:measurement.Measurement)
  })
_sym_db.RegisterMessage(Measurement)

MeasurementRequest = _reflection.GeneratedProtocolMessageType('MeasurementRequest', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENTREQUEST,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:measurement.MeasurementRequest)
  })
_sym_db.RegisterMessage(MeasurementRequest)

MeasurementResponse = _reflection.GeneratedProtocolMessageType('MeasurementResponse', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENTRESPONSE,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:measurement.MeasurementResponse)
  })
_sym_db.RegisterMessage(MeasurementResponse)

InsertResponse = _reflection.GeneratedProtocolMessageType('InsertResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSERTRESPONSE,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:measurement.InsertResponse)
  })
_sym_db.RegisterMessage(InsertResponse)

AvailableTypes = _reflection.GeneratedProtocolMessageType('AvailableTypes', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABLETYPES,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:measurement.AvailableTypes)
  })
_sym_db.RegisterMessage(AvailableTypes)


DESCRIPTOR._options = None

_MEASUREMENTRECORDER = _descriptor.ServiceDescriptor(
  name='MeasurementRecorder',
  full_name='measurement.MeasurementRecorder',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=597,
  serialized_end=770,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='measurement.MeasurementRecorder.Get',
    index=0,
    containing_service=None,
    input_type=_MEASUREMENTREQUEST,
    output_type=_MEASUREMENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAvailableTypes',
    full_name='measurement.MeasurementRecorder.GetAvailableTypes',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_AVAILABLETYPES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEASUREMENTRECORDER)

DESCRIPTOR.services_by_name['MeasurementRecorder'] = _MEASUREMENTRECORDER


_MEASUREMENTSTORE = _descriptor.ServiceDescriptor(
  name='MeasurementStore',
  full_name='measurement.MeasurementStore',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=772,
  serialized_end=861,
  methods=[
  _descriptor.MethodDescriptor(
    name='InsertData',
    full_name='measurement.MeasurementStore.InsertData',
    index=0,
    containing_service=None,
    input_type=_MEASUREMENT,
    output_type=_INSERTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEASUREMENTSTORE)

DESCRIPTOR.services_by_name['MeasurementStore'] = _MEASUREMENTSTORE

# @@protoc_insertion_point(module_scope)
