version: "3"
services:
  db:
    image: postgres:12.3
    restart: always
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - POSTGRES_PASSWORD=postgres
