version: "3"
services:
  backend:
    build: backend/
    container_name: administrator
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: house
      DB_USER: administrator
      DB_PASS: admin
    depends_on:
      - db
  db:
    image: postgres:12.3
    container_name: postgres_admin
    restart: always
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 1919:5432
    environment:
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: house
