// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: room.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 部屋番号
type RoomNumbers int32

const (
	RoomNumbers_JUN_ROOM    RoomNumbers = 0 // JUNの部屋
	RoomNumbers_SUBARU_ROOM RoomNumbers = 1 // すばるの部屋
	RoomNumbers_NORIKO_ROOM RoomNumbers = 2 // ばあちゃんの部屋
	RoomNumbers_LIVING_ROOM RoomNumbers = 3 // リビング
	RoomNumbers_ENTRANCE    RoomNumbers = 4 // 玄関
	RoomNumbers_STAIRS      RoomNumbers = 5 // 階段
	RoomNumbers_BATH_ROOM   RoomNumbers = 6 // 風呂場
	RoomNumbers_TOILET      RoomNumbers = 7 // トイレ
)

// Enum value maps for RoomNumbers.
var (
	RoomNumbers_name = map[int32]string{
		0: "JUN_ROOM",
		1: "SUBARU_ROOM",
		2: "NORIKO_ROOM",
		3: "LIVING_ROOM",
		4: "ENTRANCE",
		5: "STAIRS",
		6: "BATH_ROOM",
		7: "TOILET",
	}
	RoomNumbers_value = map[string]int32{
		"JUN_ROOM":    0,
		"SUBARU_ROOM": 1,
		"NORIKO_ROOM": 2,
		"LIVING_ROOM": 3,
		"ENTRANCE":    4,
		"STAIRS":      5,
		"BATH_ROOM":   6,
		"TOILET":      7,
	}
)

func (x RoomNumbers) Enum() *RoomNumbers {
	p := new(RoomNumbers)
	*p = x
	return p
}

func (x RoomNumbers) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomNumbers) Descriptor() protoreflect.EnumDescriptor {
	return file_room_proto_enumTypes[0].Descriptor()
}

func (RoomNumbers) Type() protoreflect.EnumType {
	return &file_room_proto_enumTypes[0]
}

func (x RoomNumbers) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomNumbers.Descriptor instead.
func (RoomNumbers) EnumDescriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

var File_room_proto protoreflect.FileDescriptor

var file_room_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x6f,
	0x6f, 0x6d, 0x2a, 0x83, 0x01, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x55, 0x4e, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x00,
	0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x55, 0x42, 0x41, 0x52, 0x55, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10,
	0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x52, 0x49, 0x4b, 0x4f, 0x5f, 0x52, 0x4f, 0x4f, 0x4d,
	0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x49, 0x56, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x4f, 0x4f,
	0x4d, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x4e, 0x54, 0x52, 0x41, 0x4e, 0x43, 0x45, 0x10,
	0x04, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x41, 0x49, 0x52, 0x53, 0x10, 0x05, 0x12, 0x0d, 0x0a,
	0x09, 0x42, 0x41, 0x54, 0x48, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06,
	0x54, 0x4f, 0x49, 0x4c, 0x45, 0x54, 0x10, 0x07, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData = file_room_proto_rawDesc
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_proto_rawDescData)
	})
	return file_room_proto_rawDescData
}

var file_room_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_room_proto_goTypes = []interface{}{
	(RoomNumbers)(0), // 0: room.RoomNumbers
}
var file_room_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		EnumInfos:         file_room_proto_enumTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_rawDesc = nil
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
